name: Django CI

on:
  push:
    branches: [ 53-restructure-backend-code ]
  pull_request:
    branches: [ 53-restructure-backend-code ]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: backend.settings
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      working-directory: backend
      run: |
        python manage.py migrate

    - name: Collect static files
      working-directory: backend
      run: |
        python manage.py collectstatic --noinput


    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: Reptrack-Production
        slot-name: production
        package: RepTrack-main/backend
