name: Django Azure Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies from requirements.txt
      working-directory: RepTrack-main
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect static files
      working-directory: RepTrack-main/backend
      run: |
        python manage.py collectstatic --noinput

    - name: Run migrations
      working-directory: RepTrack-main/backend
      run: |
        python manage.py migrate

    - name: Run Django tests
      working-directory: RepTrack-main/backend
      run: |
        python manage.py test --verbosity=2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: Reptrack-Production
        slot-name: production
        package: RepTrack-main/backend

    - name: Verify Deployment
      run: |
        curl -fsSL https://Reptrack-Production.azurewebsites.net | grep -i "Reptrack"
