name: Django Azure Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: RepTrack-main
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect static files
      working-directory: RepTrack-main/backend
      run: |
        python manage.py collectstatic --noinput

    - name: Run migrations
      working-directory: RepTrack-main/backend
      run: |
        python manage.py migrate

    - name: Run Django tests
      working-directory: RepTrack-main/backend
      run: |
        python manage.py test --verbosity=2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Azure App Settings
      uses: azure/CLI@v1
      with:
        azcliversion: "2.37.0"
        inlineScript: |
          az webapp config appsettings set --name Reptrack \
          --resource-group <RESOURCE_GROUP> \
          --settings DJANGO_SETTINGS_MODULE=RepTrack-main.backend.settings \
                     SECRET_KEY=${{ secrets.SECRET_KEY }} \
                     DATABASE_URL=${{ secrets.DATABASE_URL }} \
                     SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
                     SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: Reptrack-Production
        slot-name: production
        package: RepTrack-main
    - name: Start Django Development Server (for testing only)
      working-directory: RepTrack-main/backend
      run: |
          python manage.py runserver 0.0.0.0:8000

